import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

export interface PropertySummary {
  id?: number | null;
  attributes?: PropertyData | null;
}
export interface PropertyData {
  name: string;
  summary: string;
  heroImage: HeroImage;
}
export interface HeroImage {
  data?: StoredImage | null;
}
export interface StoredImage {
  id: number;
  attributes: StoredImageData;
}
export interface StoredImageData {
  name: string;
  alternativeText: string;
  caption: string;
  width: number;
  height: number;
  formats: Formats;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: null;
  provider: string;
  provider_metadata: ProviderMetadata;
  createdAt: string;
  updatedAt: string;
}
export interface Formats {
  large: LargeOrSmallOrMediumOrThumbnail;
  small: LargeOrSmallOrMediumOrThumbnail;
  medium: LargeOrSmallOrMediumOrThumbnail;
  thumbnail: LargeOrSmallOrMediumOrThumbnail;
}
export interface LargeOrSmallOrMediumOrThumbnail {
  ext: string;
  url: string;
  hash: string;
  mime: string;
  name: string;
  path?: null;
  size: number;
  width: number;
  height: number;
  provider_metadata: ProviderMetadata;
}
export interface ProviderMetadata {
  public_id: string;
  resource_type: string;
}

interface HomeProps {
  properties: PropertySummary[];
}

const Home: NextPage<{ properties: PropertySummary[] }, {}> = ({
  properties,
}) => {
  const house = properties[0];
  return (
    <div className="flex min-h-screen justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
        <Image
          className="w-full"
          src={
            house.attributes?.heroImage.data?.attributes.formats.small.url ||
            "https://res.cloudinary.com/ta-petrina/image/upload/v1657637777/small_panayiotis_terrace_a5ae71c62b.jpg"
          }
          alt="Sunset in the mountains"
          layout="responsive"
          width={
            house.attributes?.heroImage.data?.attributes.formats.small.width ||
            500
          }
          height={
            house.attributes?.heroImage.data?.attributes.formats.small.height ||
            375
          }
        />
        <div className="px-6 py-4">
          <div className="font-bold text-xl mb-2">{house.attributes?.name}</div>
          <p className="text-grey-darker text-base">
            {house.attributes?.summary}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch(
    "https://ta-petrina-backend.herokuapp.com/api/properties?fields[0]=name&fields[1]=summary&populate[0]=heroImage"
  );
  const data = await res.json();
  const properties = data.data;

  return {
    props: {
      properties,
    }, // will be passed to the page component as props
  };
}
